entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog: {}

log:
  level: INFO
